site_name: Create® 3 Docs
site_description: 'Documentation for the iRobot® Create® 3 robot'
site_author: 'iRobot'
#site_url: http://edu.irobot.com/create3/

repo_name: 'iRobotEducation/create3_docs'
repo_url: 'https://github.com/iRobotEducation/create3_docs'

docs_dir: docs/

theme:
  name: material
  custom_dir: theme_overrides

extra_css:
  - stylesheets/irobot-palette.css

markdown_extensions:
  - admonition

nav:
    - Home: index.md
    - Create® 3 Hardware:
      - Overview: hw/overview.md
      - Mechanical: hw/mechanical.md
      - Electrical: hw/electrical.md
      - Hookup Examples: hw/hookup.md
    - Create® 3 Setup:
      - Connect to Wi-Fi: setup/provision.md
      - Multi-Robot Setup: setup/multi-robot.md
      - ROS 2 on a Pi 4: setup/pi4.md
    - Create® 3 APIs:
      - ROS 2 Interface: api/ros2.md
      - Docking: api/docking.md
      - Drive Goals: api/drive-goals.md
      - Hazards: api/hazards.md
      - Odometry: api/odometry.md
      - Reflexes: api/reflexes.md
      - Safety: api/safety.md
      - User Interface: api/ui.md
    - Create® 3 Simulator:
      - Using the Simulator: sim/setup.md
    - Software Examples:
      - Overview: examples/overview.md
      - Driving via CLI: examples/driving-cli.md
    - Create® 3 Releases:
      - Overview: releases/overview.md
      - G.1.1: releases/g_1_1.md
