site_name: Create3 Docs
site_description: 'Documentation for the iRobot Create3 robot'
site_author: 'iRobot'
#site_url: TODO

repo_name: 'iRobotEducation/create3_docs'
repo_url: 'https://github.com/iRobotEducation/create3_docs'

docs_dir: docs/

theme:
  name: material
  custom_dir: theme_overrides

extra_css:
  - stylesheets/irobot-palette.css

markdown_extensions:
  - admonition

nav:
    - Home: index.md
    - Robot Setup:
      - Robot: robot-setup/robot.md
      - Webserver: robot-setup/webserver.md
      - Start your robot: robot-setup/start.md
    - Create3 APIs:
      - ROS 2 Interface: api/ros2.md
      - Docking: api/docking.md
      - Reflexes: api/reflexes.md
      - Safety: api/safety.md
    - Create3 Simulator:
      - Using the Simulator: sim/setup.md
